package com.kozitski.spark.domain

case class TwitUser(
                     id: Long,
                     id_str: Long,
                     name: Long,
                     screen_name: Long,
                     location: String,
                     url: String,
                     description: String,
                     translator_type: String,
//                     isProtected : Boolean,
                     verified: Boolean,
                     followers_count: Int,
                     friends_count: Int,
                     listed_count: Int,
                     favourites_count: Int,
                     statuses_count: Int,
                     created_at: String,
                     utc_offset: String,
                     time_zone: String,
                     geo_enabled: Boolean,
                     lang: String,
                     contributors_enabled: Boolean,
                     is_translator: Boolean,
                     profile_background_color: String,
                     profile_background_image_url: String,
                     profile_background_image_url_https: String,
                     profile_background_tile: Boolean,
                     profile_link_color: String,
                     profile_sidebar_border_color: String,
                     profile_sidebar_fill_color: String,
                     profile_text_color: String,
                     profile_use_background_image: Boolean,
                     profile_image_url: String,
                     profile_image_url_https: String,
                     profile_banner_url: String,
                     default_profile: Boolean,
                     default_profile_image: Boolean,
                     following: String,
                     follow_request_sent: String,
                     notifications: String
                   )
