package com.kozitski.spark.domain

case class Twit(
                 created_at: String,
                 id: String,
                 id_str: String,
                 text: String,
                 source: String,
                 truncated: Boolean,
                 in_reply_to_status_id: String,
                 in_reply_to_status_id_str: String,
                 in_reply_to_user_id: String,
                 in_reply_to_user_id_str: String,
                 in_reply_to_screen_name: String,
                 user: TwitUser,
                 geo: String,
                 coordinates: String,
                 place: String,
                 contributors: String,
                 retweeted_status: String,
                 is_quote_status: Boolean,
                 quote_count: Long,
                 reply_count: Long,
                 retweet_count: Long,
                 favourite_count: Long,
                 entities: String,
                 extended_entities: String,
                 favorited: Boolean,
                 retweeted: Boolean,
                 possibly_sensitive: Boolean,
                 filter_level: String,
                 lang: String,
                 timestamp_ms: Long
               )
